# .github/workflows/canada-push-notification.yml
name: Canada - Push Notification Pipeline

on:
  schedule:
    # Run at 12:00 PM and 6:00 PM Canada Eastern Time (UTC-5/UTC-4 depending on DST)
    # Using UTC-5 (EST) as base: 12:00 PM EST = 17:00 UTC, 6:00 PM EST = 23:00 UTC
    - cron: '0 17 * * *'  # 12:00 PM Canada Eastern Time
    - cron: '0 23 * * *'  # 6:00 PM Canada Eastern Time
  workflow_dispatch:
    inputs:
      hours_back:
        description: 'Hours to look back for popular articles'
        required: false
        default: '6'
        type: string

jobs:
  push_notification:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Restore Firebase credential JSON
        run: echo "${{ secrets.FIREBASE_CREDENTIAL_JSON }}" | base64 -d > serviceAccountKey.json

      - name: Run push notification pipeline for Canada
        env:
          FIREBASE_CREDENTIAL_PATH: serviceAccountKey.json
          FIREBASE_FUNCTION_URL: ${{ secrets.FIREBASE_FUNCTION_URL }}
          NEWS_API_URL: ${{ secrets.CANADA_API_URL }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          hours_back="${{ github.event.inputs.hours_back || '6' }}"
          python pipeline/push_notification_pipeline.py canada $hours_back