name: Russia - Daily Popular Pipeline

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  daily_popular:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Restore Firebase credential JSON
        run: echo "${{ secrets.FIREBASE_CREDENTIAL_JSON }}" | base64 -d > serviceAccountKey.json

      - name: Run daily popular pipeline for Russia
        env:
          FIREBASE_CREDENTIAL_PATH: serviceAccountKey.json
          AI_URL: ${{ secrets.AI_URL }}
          NEWS_API_URL: ${{ secrets.RUSSIA_API_URL }}
        run: python pipeline/daily_popular_pipeline.py russia